github 101
farm-ng/amiga-dev-kit pull request #130
Opened 2023-02-02 23:23 UTC by jerrycowell96

2023-02-03 13:18 UTC, edgarriba requested changes
@jerrycowell96 where is the file ? is this PR ready to review or should be draft ?

2023-02-07 21:44 UTC, edgarriba approved these changes
LGTM. Just minimum formatting changes and simplify the pre-commit steps

2023-02-07 21:44 UTC, edgarriba commented on website/docs/support/github-101.md
> +pre-commit run --all-files
this is not really necessary if we do install pre-commit before. I'd add a previous step `pre-commit install`

2023-02-07 21:44 UTC, edgarriba commented on website/docs/support/github-101.md
> +
```suggestion
```

2023-02-07 21:44 UTC, edgarriba commented on website/docs/support/github-101.md
> +## Personal Access Token
```suggestion
## Personal Access Token

```

2023-02-07 21:44 UTC, edgarriba commented on website/docs/support/github-101.md
> +Prerequisites
```suggestion
Prerequisites:

```

2023-05-01 18:04 UTC, Hackerman342 commented
@jerrycowell96 I'd recommend getting this updated and merged in!

2023-09-29 15:50 UTC, Hackerman342 commented
@guilhermedemouraa I've just updated these docs. Can you please give them a review to make sure they seem clear? Please merge if so.

2023-09-29 17:19 UTC, guilhermedemouraa commented on website/docs/support/github-101.md
> +## Set up an ssh key
I'd probably rename this section, as its content isn't necessarily just about creating an SSH key

2023-09-29 17:26 UTC, guilhermedemouraa approved these changes

2023-09-29 18:34 UTC, edgarriba approved these changes

2023-09-29 19:52 UTC, merged