launcher
farm-ng/amiga-dev-kit pull request #296
Opened 2024-04-12 00:46 UTC by AgustinBRodriguez

Changes to documentation

Added a Launcher App page to the User manual 
Added a Deprecated page to the Reference section and nested Brain v1 and Filter App.
made the necessary changes to 
https://github.com/farm-ng/Amiga-support-issues/issues/231#issuecomment-2050188556

2024-04-16 17:52 UTC, AgustinBRodriguez commented
@guilhermedemouraa can you please add a few lines to describe/explain robot localization and track following?. The serial interface field in the ntrip section also needs a brief description. Let me know if you have any questions. Thank you

2024-04-19 21:55 UTC, guilhermedemouraa requested changes

2024-04-19 23:04 UTC, AgustinBRodriguez commented on website/docs/apps/launcher/README.md
> +
Added

2024-04-19 23:04 UTC, AgustinBRodriguez commented on website/docs/apps/filter_app/README.md
> +of the launcher app and can be found under the settings tab.
added

2024-04-19 23:07 UTC, AgustinBRodriguez commented on website/docs/apps/launcher/README.md
> +For an in dept exploration of the Amiga Services follow this [link](/docs/concepts/canbus_service/).
modified

2024-04-19 23:10 UTC, AgustinBRodriguez commented on website/docs/apps/launcher/README.md
> +For an in dept exploration of the Amiga Services follow this [link](/docs/concepts/canbus_service/).
will do

2024-04-19 23:29 UTC, AgustinBRodriguez commented on website/docs/apps/launcher/README.md
> +:::tip
clarified

2024-04-24 23:15 UTC, merged