Amiga farm ng com update
farm-ng/amiga-dev-kit pull request #315
Opened 2024-06-05 23:36 UTC by MScatolin

Added hardware documentation, updated dashboard settings.

2024-06-06 17:08 UTC, AgustinBRodriguez commented on website/docs/apps/autoplot_app/README.md
This is prone to happen when your Robot is more than more than 12 km (8 miles) away from your base station,


when operating under cloudy conditions, and/or changing local topography.


If you see tracks with an expressive offset (larger than 0.5 m or 2 feet), verify that your
RTK-correction service provider is NOT using a VRS (Virtual Reference Station).These stations change
their reference system after every reboot and are not currently supported. We recommend
switching to a service provider that uses a static base station or that you record new paths after every reboot.

2024-06-06 18:02 UTC, AgustinBRodriguez commented on website/docs/dashboard/dashboard_user_guide.md
Starting with Dashboard Firmware `v0.5.0` the Amiga Brain has now tool control capabilities.

**mention the Amiga OS version that enabled tool control on the brain/browser?

Therefore, when Auto Control is ENABLED, a blue outline will appear around the Dashboard and the pendant commands will be bypassed. Tool control is thus carried out in the Autoplot app, a browser window, or your custom application.<br/><br/>

If manual control is needed, disable Auto Control from the Dashboard.

2024-06-06 21:22 UTC, AgustinBRodriguez commented on website/docs/concepts/gps_service/README.md
Currently, RTK corrections rely on a static base station. If your service provider issues RTK corrections with respect to a VRS (Virtual Reference Station), your coordinates will experience a significant offset after every reboot.

2024-06-06 21:29 UTC, AgustinBRodriguez commented on website/docs/hardware/assets/can.png
These are cool. I think we can get CAD drawings from tony to show the actual components.

2024-06-06 21:38 UTC, AgustinBRodriguez commented on website/docs/hardware/charging.md
Your charger can output power at 2 A (max), which will charge your 15 Ah in about 6 hours,
depending on the buffer value you have selected on the Dashboard settings (i.e `batt-lo`). 



Alternatively, you can connect the provided fast charger directly to the spare Anderson
connectors in your Amiga. The fast charger will provide XXXXXXX Amps and will enable you to get back to a full charge in approximately XXXXXX hours   

Check in with Travis to find out the current output of the fast charger and the charge time

2024-06-06 22:16 UTC, AgustinBRodriguez commented on website/docs/hardware/electronics.md
This circuit provides power to all other circuits and the motors, operating at 48 VDC. Power is
drawn from the batteries via C14 connectors and distributed using the cross bar and truck bar
harnesses via Anderson connectors.

the A-D harness is secured to the truck bars as it is also the case for the B-C harness on the other side. The cross harness that links the two sides is secured to the crossbar using fir trees and ziptides... 

"motor controllers..... and other tools such as the H-Bridge and PTO when these are available.""....

Your Amiga uses a CAN network to send control messages between the dashboard, pendant, motors, and
tools (if available). 



Inside each fork panel, NMEA-2000 CAN hubs connect provide a connection point to tie the motor controllers to the CAN network. Extra ports are available to connect additional CAN devices.
Termination resistors are placed at either end of the CAN network to ensure that the CAN signals are not reflected from the cable ends. For best results, the CAN bus termination should match the nominal impedance of the cables, which for ISO 11898-2 (high speed CAN) is specified at 120 Ohm. 


The users will never see the black/red connections on their M12 cables unless the cables have been severed. The fuse to look at would be the one in the Buck converter. (clarity) inspect its integrity....... 

When you can't detect power on your CAN bus (red and black wires), there is a high chance you have
a blown fuse. Inspect your fuse visually  and/or using a multimeter before proceeding with
troubleshooting.



The primary role of the E-stop circuit is to cut power from the motor controllers at start up (preventing any possibility that the Amiga would simply take off) as well as in emergency situations when the Amiga must be stopped. 


CAUTION: Engaging the E-stop button cuts power to the motor controllers but it does not provide a braking system. Be prepare for the Amiga to roll over if the button is engaged while the robot sits at an incline. 

  

 
The ESTOP circuit is crucial for your Amiga, receiving 24 VDC from the Power Buck and distributing
it via M8 connectors to the motor controllers and the physical STOP button.




The T's are simply junctions that allow for the creation of a closed loop system across all the peripherals attached to the E-Stop circuit.. Additional components such as the H-bride and PTO must be tied to the E-stop circuit for safety purposes. This is done by adding t junctions and cables to bring in these peripherals into the loop. 

Inside each fork panel, blue M8 Tees allow motor controllers to receive the E-STOP signal. Extra
tees can be added for additional E-STOP cables, useful for operating tools. Farm-ng PTOs and
H-Bridges require an E-STOP signal to operate.

2024-06-06 22:36 UTC, AgustinBRodriguez commented on website/docs/hardware/electronics_brain.md
This isn't very clear to me. The brain is powered by way of an M12 cable that simultaneously provides the required 24volt power supply and CAN network communications.  Autonomy is a combination of Brain Apps and the CAN messages sent back to the dashboard/motor controllers.  a bit of clarity here would help. 


When your Amiga is equipped with a Brain and its typical accessories, you will be able to create
applications that interact and record CAN messages and other software services to make your Amiga
an autonomous robot. To accomplish that, your Brain must be connected to the CAN bus.

I am not aware that the Brain is sold as a separate unit away from the Intelligence Kit (Brain, POE Switch, 2 Luxonics cameras, GPS Antenna and related cables.) 

The Brains is usually purchased with the other parts of our Intelligence Kit: cameras, GPS antenna,
and a Power over Ethernet (PoE) Switch:



The brain draws power from the CAN BUS 
The POE switch does not. It receives a 48Volt input via the anderson connectors. This is parsed thru the dual bucks and outputted to the POE switch via an M12 cable that comes directly from the bucks (NOT the CAN BUS)

Note that both the Brain and the PoE switch drawn power from the CAN bus (24 VDC), with the switch
using 2 power bucks to convert 24 VDC to 48 VDC and maintain redundancy.




....M12 Cable from the Bucks to the M12 connection on the brain.... 
:::warning Caution
When changing connections on the PoE and/or Brain, make sure you do not connect the power cable
\from the PoE (the one leaving the power bucks) to the Brain. **Doing so will cause electrical
and/or thermal damage to your Amiga's Brain.**
:::





The PoE camera ports can be identified by the orange ring surrounding each of the ports. The other two ports are used for data transfer/communications.  (i.e. between the switch and the Brain).

 
The open ports on your PoE Switch can be used to add more camera (up to 4 in total) and other
ethernet devices  (you will need a NMEA-2000 to Ethernet cable adapter).



Changed configurations... Each time you move the the GPS antenna and/or the IMU (oak 0) you must change your robot's geometry to conform with the new locations of these components. Doing so will ensure accurate navigation. All measurements are taking from the robot's center.  

:::info Changing Intelligence kit mount
When changing where the Intelligence Kit is mounted in your Amiga, make sure you update the Robot
Geometry parameters on your [Brain Settings](../apps/launcher/#robot-geometry).
:::

2024-06-06 22:46 UTC, AgustinBRodriguez commented on website/docs/hardware/mechanics.md
0.6 %??? in what direction???

* The ratio between your Amiga's length and width should be 0.6 or less.
  * E.g., a 48" wheelbase Amiga should have a track width of approximately `48 * 0.6 ~ 27 inches`.



It can lead to overheating and permanent damage. This is highly dependant on.....

A fail safe mechanism to protect the motors from overheating is hard coded into the Dashboard's firmware. To reduce the risk of damage due to overheating, our motors will stop for cooling once they reach 80°C
(176°F). 
 
:::warning Amiga's geometry
Operating with larger ratios will lead to premature overheating of your motors and eventually
permanent damage. To reduce this risk, our motors will stop for cooling once they reach 80°C
(176°F). This is highly dependent on how your load is configured and the service (turn radius,
frequency, type, etc.)
:::

when using an Intelligence Kit

:::info Amiga's Geometry when using Intelligence Kit
If you have an Intelligence Kit, remember to change the `wheelbase` parameter on your
[Brain Settings](../apps/launcher/#robot-geometry).<br/><br/>
**If there is a mismatch between your physical setup and your geometry settings in your Brain, you
will likely experience offsets when following tracks.**


This is called the mast... (It holds the Dashboard, E-stop and the pendant) the clamp is used to secure it to anyone of the cross/truck bars of the Amiga

## Pendant and Intelligence Kit Pole

2024-06-06 22:51 UTC, AgustinBRodriguez commented on website/docs/hardware/mechanics_otr.md
The over the row kit is different from the Amiga suspension kit (as far as I know; check in with Tony). There are many more parts to convert a base a Amiga to an over the row unit (and as far as I know it is not a suspension kit).

I think this section needs a lot more input and a clarity from HW engineering.

2024-06-06 22:53 UTC, AgustinBRodriguez commented on website/sidebars.js
great work. I think that all these sections are needed and will certainly help with both support issues and user experience. Lets work together to make them even better.

2024-06-06 22:57 UTC, AgustinBRodriguez requested changes
yo! I hope these comments add clarity/perspective to all the fabulous work you put into these sections. They are not intended as rewrites etc.. Nothing but the good stuff!!! I believe that clarity and a true understanding of the content and/or the intended message therein will easily translate to the user!  there are parts that I did not clearly understand. Let me know how else I can help!!

2024-06-07 02:12 UTC, MScatolin commented on website/docs/apps/autoplot_app/README.md
improved clarity on the first part. Implemented the second.

2024-06-07 02:17 UTC, MScatolin commented on website/docs/dashboard/dashboard_user_guide.md
We tested and yellow outline is already enough to have the pendant commands bypassed. Adjusted for and updated.

2024-06-07 02:19 UTC, MScatolin commented on website/docs/concepts/gps_service/README.md
I think RTK corrections alludes to the messages the company provides. We transform those messages to NED frame. I'll merge the two snippets.

2024-06-07 02:23 UTC, MScatolin commented on website/docs/hardware/assets/can.png
I don't think we do have them at the moment. If we do, or the guys want to draw anytime in the next week or so, we can wait, otherwise I think we should replace it later.

2024-06-07 02:34 UTC, MScatolin commented on website/docs/hardware/charging.md
reviewed all comments for clarity.

2024-06-07 03:01 UTC, MScatolin commented on website/docs/hardware/electronics.md
Edited where you commented.

2024-06-07 03:35 UTC, MScatolin commented on website/docs/hardware/mechanics_otr.md
Good point... there are OTR that don't have suspension. Clarified.

2024-06-14 23:06 UTC, MScatolin commented on website/docs/hardware/electronics_brain.md
changed picture and the lines you mentioned.

2024-06-14 23:09 UTC, MScatolin commented on website/docs/hardware/assets/can.png
Claire asked to push with the current drawings and maybe improve later. keeping them for now.

2024-06-14 23:09 UTC, MScatolin commented on website/docs/hardware/mechanics.md
improved where commented.

2024-06-21 21:47 UTC, AgustinBRodriguez approved these changes

2024-06-26 21:10 UTC, merged